---
title: "LINEX_for_BM"
author: "Deepak Bastola"
date: "August 18, 2019"
output: pdf_document
---

```{r}
# Stochastic Gradient descent
# For LINEX (LInear EXponential) Objective Function

library(mcmcse)
library(parallel)
require(latex2exp)

# model matrix
# fixed correlation, n, and batch sizes
# phi = 0.95, n = 1e4, b = 159, r=2, s=4

chain <- function(niter, n, phi, b){

ar1sim <- function (n, rho) {
  vec <- vector("numeric", n)
  vec[1] <- 0
  for (i in 2:n){vec[i] <- rho * vec[i - 1] + rnorm(n=1, mean = 0, sd = 1)}
  vec
}

#generate the model matrix
pmt <- proc.time()
mat <- mclapply(1:niter, function(i) ar1sim(n,phi), 
                mc.preschedule = TRUE, mc.cores = 6)
proc.time() - pmt

pmt <- proc.time()
design <- mclapply(1:niter, function(i)  sapply(1:length(b), function(j) 
  mcse(mat[[i]], size = b[j], method = "bm")$se^2*n), 
  mc.preschedule = TRUE, mc.cores = 4)
proc.time() - pmt

sigma.true <- 1/(1-phi)^2
scratch <- lapply(1: length(design), function(i) append(sigma.true, design[[i]]))
output <- matrix(unlist(scratch), ncol = 4, byrow = TRUE)
return(output)
}


out1 <- chain(5000, 1e4, 0.95, c(150, 150/2, 150/4))

# partial derivatives, evaluated at single point
partial.deriv <- function(y, x, c, k, alpha, lam, gam){
  ans <- sapply(1:nrow(x), function(i)
    c*k*(exp(c*(alpha%*%x[i,] - y[i,]))-1)%*%x[i,] + 2*lam*alpha + rep(1,3)*gam)
mean(ans)  
}

# stochastic gradient descent

gradient.descent <- function(mat, alpha, c, k, lam, gam, eta){
  
  mat <- data.frame(mat)
  # initialize
  alpha <- matrix(alpha, nrow = 1)
  alphaIter <- matrix(NA, nrow(mat), 3)
  
  # set seed
  set.seed(123)
  
for (i in 1: nrow(mat)){
  design <- mat[sample(nrow(mat), 50, replace = TRUE),]
  x <- as.matrix(design[,2:4])
  y <- as.matrix(design[,1])
    
  alpha <- alpha - eta * partial.deriv(y, x, c, k, alpha, lam, gam)
  alphaIter[i,] <- alpha
    
  }
return(alphaIter)  
  
  }


x1 <- gradient.descent(out1, alpha = c(-1.2,0.5,0.9), c = -0.005, k = 1, lam = .7, gam = 3, eta = 0.0001)
#x2 <- gradient.descent(output, alpha = c(0.5,-.1,-.1), c = -0.005, k = 1, lam = 0.2, gam = 1, eta = 0.0001)
plot(rowSums(x1), type = "l")

```



```{r}
# Plot of Linex function

f <- function(x) (exp(-0.02*(x-400)) + 0.02*(x-400) -1)/0.1
curve(f, 300,500)

linexb <- function(n,b,c,k,phi){

# Markov Chain
ar1sim <- function (n, rho) {
  vec <- vector("numeric", n)
  vec[1] <- 0
  for (i in 2:n){vec[i] <- rho * vec[i - 1] + rnorm(n=1, mean = 0, sd = 1)}
  vec
}
                                                                                                                                                            
out <- ar1sim(n, phi)
sigma.true <- 1/(1-phi)^2
sigma.bm <- lapply(1:length(b), function(i) mcse(out, size = b[i], method = "bm")$se^2*n)

linexloss <- sapply(1:length(b), function(i) 
  k*(exp(c*(sigma.bm[[i]] - sigma.true))-c*(sigma.bm[[i]] - sigma.true) -1))
return(linexloss)
}


out <- ar1sim(1e4, 0.95)
linexb(1e4, 100, -0.005, 0.1, 0.95)
mcse(out, size = 100, method = "bm")$se^2*n

```


```{r}
#Simulation
n <- 1e4
c <- -0.005
k <- 0.1
phi = 0.95
b <- seq(floor(n^(1/3)), floor(n^(5/8)),1) 

nrep <- 5000
start.time <- Sys.time()
sim95 <- mclapply(1:nrep, function(i) linexb(n, b, c , k , phi = 0.95), mc.preschedule = TRUE, mc.cores = 7)
sim90 <- mclapply(1:nrep, function(i) linexb(n, b, c , k , phi = 0.90), mc.preschedule = TRUE, mc.cores = 7)
sim85 <- mclapply(1:nrep, function(i) linexb(n, b, c , k , phi = 0.85), mc.preschedule = TRUE, mc.cores = 7)
sim80 <- mclapply(1:nrep, function(i) linexb(n, b, c , k , phi = 0.80), mc.preschedule = TRUE, mc.cores = 7)
end.time <- Sys.time()
end.time - start.time

res95 <- colMeans(do.call(rbind, sim95))
res90 <- colMeans(do.call(rbind, sim90))
res85 <- colMeans(do.call(rbind, sim85))
res80 <- colMeans(do.call(rbind, sim80))

b95 <- b[which.min(res95)]
b90 <- b[which.min(res90)]
b85 <- b[which.min(res85)]
b80 <- b[which.min(res80)]

pdf("b_opt.pdf")
par(mfrow = c(2,2))
plot(b, res95, type = "l", ylab = "Expected LINEX loss", xlab = "b", main = TeX('$\\phi = 0.95$'), lty = 1, lwd = 2, col = "blue")
abline(v= b95, col = "green")
text(b95+9, 0.08, expression(b[opt] == 159))

plot(b, res90, type = "l", ylab = "Expected LINEX loss", xlab = "b", main = TeX('$\\phi = 0.90$'), lty = 1, lwd = 2, col = "blue")
abline(v= b90, col = "green")
text(b90+9, 0.00138, expression(b[opt] == 100))

plot(b, res85, type = "l", ylab = "Expected LINEX loss", xlab = "b", main = TeX('$\\phi = 0.85$'), lty = 1, lwd = 2, col = "blue")
abline(v= b85, col = "green")
text(b90+9, 0.00015, expression(b[opt] == 68))

plot(b, res80, type = "l", ylab = "Expected LINEX loss", xlab = "b", main = TeX('$\\phi = 0.80$'), lty = 1, lwd = 2, col = "blue")
abline(v= b80, col = "green")
text(b90+9, 0.00004, expression(b[opt] ==  57))
par(mfrow = c(1,1))
dev.off()


```


```{r}
# simulation n = 1e5
n <- 1e4
c <- -0.05
k <- 0.2

b <- seq(floor(n^(1/3)), floor(n^(5/8)),1) 

nrep <- 500

start.time <- Sys.time()
sim95x <- mclapply(1:nrep, function(i) linexb(n, b, c , k , phi = 0.95), mc.preschedule = TRUE, mc.cores = 7)
sim90x <- mclapply(1:nrep, function(i) linexb(n, b, c , k , phi = 0.90), mc.preschedule = TRUE, mc.cores = 7)
sim85x <- mclapply(1:nrep, function(i) linexb(n, b, c , k , phi = 0.85), mc.preschedule = TRUE, mc.cores = 7)
sim80x <- mclapply(1:nrep, function(i) linexb(n, b, c , k , phi = 0.80), mc.preschedule = TRUE, mc.cores = 7)
end.time <- Sys.time()
end.time - start.time

res95x <- colMeans(do.call(rbind, sim95x))
res90x <- colMeans(do.call(rbind, sim90x))
res85x <- colMeans(do.call(rbind, sim85x))
res80x <- colMeans(do.call(rbind, sim80x))

b95x <- b[which.min(res95x)]
b90x <- b[which.min(res90x)]
b85x <- b[which.min(res85x)]
b80x <- b[which.min(res80x)]

pdf("b_optx.pdf")
par(mfrow = c(2,2))
plot(b, res95x, type = "l", ylab = "Expected LINEX loss", xlab = "b", main = TeX('$\\phi = 0.95$'), lty = 1, lwd = 2, col = "blue")
abline(v= b95x, col = "green")
text(b95x+9, 0.08, expression(b[opt] == 159))

plot(b, res90x, type = "l", ylab = "Expected LINEX loss", xlab = "b", main = TeX('$\\phi = 0.90$'), lty = 1, lwd = 2, col = "blue")
abline(v= b90x, col = "green")
text(b90x+9, 0.00138, expression(b[opt] == 100))

plot(b, res85x, type = "l", ylab = "Expected LINEX loss", xlab = "b", main = TeX('$\\phi = 0.85$'), lty = 1, lwd = 2, col = "blue")
abline(v= b85x, col = "green")
text(b90x+9, 0.00015, expression(b[opt] == 68))

plot(b, res80x, type = "l", ylab = "Expected LINEX loss", xlab = "b", main = TeX('$\\phi = 0.80$'), lty = 1, lwd = 2, col = "blue")
abline(v= b80x, col = "green")
text(b90x+9, 0.00004, expression(b[opt] ==  57))
par(mfrow = c(1,1))
dev.off()


```
